version: '3.7'
services:
  config-server:
    image: config-server:v1
    ports:
      - "8001:8001"
    restart: always
    networks: 
      - mynetwork
  eureka-server:
    image: eureka-server:v1
    ports:
      - "8761:8761"
    restart: always
    networks: 
      - mynetwork
  microservice-mongo:
    image: mongo:4.0.4
    ports:
      - "27017:27017"
    restart: always
    networks: 
      - mynetwork  
networks:
  mynetwork: