version: '3.7'
services:
  zuul-server:
    image: zuul-server:v1
    ports:
      - "8020:8020"
    restart: always
    networks: 
      - mynetwork
    depends_on: 
      - config-server
      - eureka-server
      - microservice-mongo
      - bank-account-main
      - fixed-term-vip
      - transaction-vip
networks:
  mynetwork: